# Generated by Django 2.1.2 on 2018-10-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('usename', models.CharField(blank=True, max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
